Import(['lev_comp', 'env'])

def lev_comp_gen(source, target, env, for_signature):
    return '{} {}'.format(lev_comp, source[0])

lev_comp_bld = env.Builder(generator = lev_comp_gen)

env.Append(BUILDERS = {'Level' : lev_comp_bld})

env.Level('sokoban.something', 'sokoban.des')
